url: "https://axel.havukangas.fi"
plugins:
  - jekyll-sitemap
defaults:
  - scope:
      path: "**/*.pdf"
    values:
      sitemap: false
  - scope:
      path: "stuff/irssi-remote-client/**/*"
    values:
      sitemap: false
