on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'
    - name: Build
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
    - name: Publish
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: >
          s3 sync ./_site/ s3://aeirola.iki.fi 
          --region eu-central-1
          --acl public-read
          --cache-control max-age=600
          --delete
